[".local/share/delta-catppuccin"]
    type = "archive"
    url = "https://github.com/catppuccin/delta/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/bat/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["*/themes/**"]

[".config/alacritty/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/alacritty/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/catppuccin-*.toml"]

[".config/btop/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/btop/archive/main.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["*/themes/**"]

[".local/share/rofi/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/rofi/archive/refs/heads/main.zip"
    exact = true
    stripComponents = 6
    refreshPeriod = "168h"
    include = ["*/basic/.local/share/rofi/themes/**"]

[".config/hypr/frappe.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/hyprland/refs/heads/main/themes/frappe.conf"
    refreshPeriod = "168h"

