return {
	-- {
	-- 	"ray-x/go.nvim",
	-- 	dependencies = { -- optional packages
	-- 		"ray-x/guihua.lua",
	-- 		"neovim/nvim-lspconfig",
	-- 		"nvim-treesitter/nvim-treesitter",
	-- 		"theHamsta/nvim-dap-virtual-text",
	-- 	},
	-- 	keys = {
	-- 		{
	-- 			"<leader>ga",
	-- 			"<cmd>GoAlt<cr>",
	-- 			desc = "Open alternative go file",
	-- 		},
	-- 		{
	-- 			"<leader>gas",
	-- 			"<cmd>GoAltS<cr>",
	-- 			desc = "Open alternative go file in split",
	-- 		},
	-- 		{
	-- 			"<leader>gav",
	-- 			"<cmd>GoAltV<cr>",
	-- 			desc = "Open alternative go file in vertical split",
	-- 		},
	-- 		{
	-- 			"<leader>gt",
	-- 			"<cmd>GoTest -n<cr>",
	-- 			desc = "Test nearest",
	-- 		},
	-- 		{
	-- 			"<leader>gta",
	-- 			"<cmd>GoTest<cr>",
	-- 			desc = "Test all",
	-- 		},
	-- 	},
	-- 	config = function()
	-- 		require("go").setup()
	-- 	end,
	-- 	event = { "CmdlineEnter" },
	-- 	ft = { "go", "gomod" },
	-- 	build = ':lua require("go.install").update_all_sync()', -- if you need to install/update all binaries
	-- },
}
